# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Spoom' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Spoom

  target 'SpoomTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Spoom-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Spoom-tvOS

  target 'Spoom-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
